"""canonical domain schema

Revision ID: fa73e07500b5
Revises: 
Create Date: 2026-08-06 16:39:48.281332+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa73e07500b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_releases',
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('accountable_owner', sa.String(length=255), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('release_status', sa.String(length=32), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('release_id', name=op.f('pk_agent_releases')),
    sa.UniqueConstraint('agent_id', 'version', name=op.f('uq_agent_releases_agent_id'))
    )
    with op.batch_alter_table('agent_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_releases_agent_id'), ['agent_id'], unique=False)

    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('audit_plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('horizon_start', sa.Date(), nullable=True),
    sa.Column('horizon_end', sa.Date(), nullable=True),
    sa.Column('coverage_policy_json', sa.JSON(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_audit_plans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_audit_plans')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name=op.f('uq_audit_plans_tenant_id'))
    )
    with op.batch_alter_table('audit_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('controls',
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_ref', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_controls_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', name=op.f('pk_controls')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_controls_tenant_id'))
    )
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controls_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('engagement_templates',
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('audit_pack_ref', sa.String(length=255), nullable=False),
    sa.Column('objectives_json', sa.JSON(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('preflight_policy_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_engagement_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_engagement_templates')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name=op.f('uq_engagement_templates_tenant_id'))
    )
    with op.batch_alter_table('engagement_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=160), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_idempotency_records_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_idempotency_records_tenant_id'))
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('organization_profiles',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('headquarters_country', sa.String(length=2), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('canonical_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_organization_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_organization_profiles')),
    sa.UniqueConstraint('tenant_id', 'version', name=op.f('uq_organization_profiles_tenant_id'))
    )
    with op.batch_alter_table('organization_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_outbox_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_outbox_events_tenant_id'))
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_outbox_unpublished', ['published_at', 'occurred_at'], unique=False)

    op.create_table('risks',
    sa.Column('risk_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inherent_impact', sa.Float(), nullable=True),
    sa.Column('inherent_likelihood', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('control_maturity', sa.Float(), nullable=True),
    sa.Column('residual_risk', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_risks_confidence_range')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_risks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', name=op.f('pk_risks')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_risks_tenant_id'))
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('role_assignments',
    sa.Column('assignment_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_role_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('tenant_id', 'principal_type', 'principal_id', 'role', 'scope_type', 'scope_id', name=op.f('uq_role_assignments_tenant_id'))
    )
    with op.batch_alter_table('role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_assignments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_schedules',
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('audit_period_rule_json', sa.JSON(), nullable=False),
    sa.Column('blackout_policy_json', sa.JSON(), nullable=False),
    sa.Column('preflight_policy_json', sa.JSON(), nullable=False),
    sa.Column('launch_mode', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['audit_plans.plan_id'], name=op.f('fk_audit_schedules_plan_id_audit_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['engagement_templates.template_id'], name=op.f('fk_audit_schedules_template_id_engagement_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_audit_schedules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_audit_schedules')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name=op.f('uq_audit_schedules_tenant_id'))
    )
    with op.batch_alter_table('audit_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_schedules_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_universe_entities',
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('criticality >= 0 AND criticality <= 5', name=op.f('ck_audit_universe_entities_criticality_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['organization_profiles.profile_id'], name=op.f('fk_audit_universe_entities_profile_id_organization_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_audit_universe_entities_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_audit_universe_entities')),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'external_ref', name=op.f('uq_audit_universe_entities_tenant_id'))
    )
    with op.batch_alter_table('audit_universe_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_universe_entities_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_universe_entities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('engagements',
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('audit_pack_ref', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('scope_version', sa.Integer(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_engagements_period_order')),
    sa.ForeignKeyConstraint(['template_id'], ['engagement_templates.template_id'], name=op.f('fk_engagements_template_id_engagement_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_engagements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('engagement_id', name=op.f('pk_engagements')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_engagements_tenant_id'))
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('organization_facts',
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('fact_key', sa.String(length=160), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['organization_profiles.profile_id'], name=op.f('fk_organization_facts_profile_id_organization_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_organization_facts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_organization_facts')),
    sa.UniqueConstraint('profile_id', 'fact_key', name=op.f('uq_organization_facts_profile_id'))
    )
    with op.batch_alter_table('organization_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_facts_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_facts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('risk_control_links',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('risk_id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('coverage', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], name=op.f('fk_risk_control_links_control_id_controls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.risk_id'], name=op.f('fk_risk_control_links_risk_id_risks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_risk_control_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', name=op.f('pk_risk_control_links')),
    sa.UniqueConstraint('risk_id', 'control_id', name=op.f('uq_risk_control_links_risk_id'))
    )
    with op.batch_alter_table('risk_control_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_control_links_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('engagement_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('task_key', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('definition_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_agent_role', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_refs_json', sa.JSON(), nullable=False),
    sa.Column('output_refs_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('execution_policy_json', sa.JSON(), nullable=False),
    sa.Column('model_policy', sa.String(length=128), nullable=True),
    sa.Column('tool_policy', sa.String(length=128), nullable=True),
    sa.Column('human_gate', sa.String(length=128), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_engagement_tasks_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_engagement_tasks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_engagement_tasks')),
    sa.UniqueConstraint('engagement_id', 'task_key', name=op.f('uq_engagement_tasks_engagement_id')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_engagement_tasks_tenant_id'))
    )
    with op.batch_alter_table('engagement_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_tasks_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_tasks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_tasks_claimable', ['status', 'lease_expires_at'], unique=False)

    op.create_table('entity_relationships',
    sa.Column('relationship_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['audit_universe_entities.entity_id'], name=op.f('fk_entity_relationships_source_entity_id_audit_universe_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['audit_universe_entities.entity_id'], name=op.f('fk_entity_relationships_target_entity_id_audit_universe_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_entity_relationships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', name=op.f('pk_entity_relationships')),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relationship_type', 'valid_from', name=op.f('uq_entity_relationships_source_entity_id'))
    )
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_relationships_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('business_objective', sa.Text(), nullable=True),
    sa.Column('risk_statement', sa.Text(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('observed_condition', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('affected_population_json', sa.JSON(), nullable=False),
    sa.Column('limitations_json', sa.JSON(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_findings_confidence_range')),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_findings_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_findings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_findings')),
    sa.UniqueConstraint('engagement_id', 'code', 'version', name=op.f('uq_findings_engagement_id'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('schedule_occurrences',
    sa.Column('occurrence_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('nominal_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_schedule_occurrences_engagement_id_engagements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['audit_schedules.schedule_id'], name=op.f('fk_schedule_occurrences_schedule_id_audit_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_schedule_occurrences_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('occurrence_id', name=op.f('pk_schedule_occurrences')),
    sa.UniqueConstraint('engagement_id', name=op.f('uq_schedule_occurrences_engagement_id')),
    sa.UniqueConstraint('schedule_id', 'nominal_due', name=op.f('uq_schedule_occurrences_schedule_id'))
    )
    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approval_decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_approval_decisions_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_approval_decisions_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_approval_decisions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_approval_decisions'))
    )
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_decisions_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_audit_events_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['engagement_tasks.task_id'], name=op.f('fk_audit_events_task_id_engagement_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_audit_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('limitations_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_claims_confidence_range')),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_claims_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_claims_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['engagement_tasks.task_id'], name=op.f('fk_claims_task_id_engagement_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_claims_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evidence_records',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('object_uri', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('tainted', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_evidence_records_nonnegative_size')),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_evidence_records_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['engagement_tasks.task_id'], name=op.f('fk_evidence_records_task_id_engagement_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_evidence_records_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence_records')),
    sa.UniqueConstraint('tenant_id', 'source_locator', 'content_sha256', name=op.f('uq_evidence_records_tenant_id'))
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_records_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('execution_traces',
    sa.Column('trace_row_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_release_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_release_id'], ['agent_releases.release_id'], name=op.f('fk_execution_traces_agent_release_id_agent_releases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_execution_traces_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['engagement_tasks.task_id'], name=op.f('fk_execution_traces_task_id_engagement_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_execution_traces_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_row_id', name=op.f('pk_execution_traces')),
    sa.UniqueConstraint('tenant_id', 'trace_id', name=op.f('uq_execution_traces_tenant_id'))
    )
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_traces_agent_release_id'), ['agent_release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_traces_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_traces_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_traces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('management_responses',
    sa.Column('response_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=128), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_management_responses_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_management_responses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', name=op.f('pk_management_responses')),
    sa.UniqueConstraint('finding_id', 'version', name=op.f('uq_management_responses_finding_id'))
    )
    with op.batch_alter_table('management_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_management_responses_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_management_responses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('remediation_actions',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('owner_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('escalation_policy_json', sa.JSON(), nullable=False),
    sa.Column('closure_evidence_required', sa.Boolean(), nullable=False),
    sa.Column('declared_complete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_remediation_actions_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_remediation_actions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_remediation_actions'))
    )
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_actions_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('dependency_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on_task_id', sa.String(length=64), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['engagement_tasks.task_id'], name=op.f('fk_task_dependencies_depends_on_task_id_engagement_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['engagement_tasks.task_id'], name=op.f('fk_task_dependencies_task_id_engagement_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_task_dependencies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependency_id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name=op.f('uq_task_dependencies_task_id'))
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claim_evidence_links',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_claim_evidence_links_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.evidence_id'], name=op.f('fk_claim_evidence_links_evidence_id_evidence_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_claim_evidence_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', name=op.f('pk_claim_evidence_links')),
    sa.UniqueConstraint('claim_id', 'evidence_id', 'relationship', name=op.f('uq_claim_evidence_links_claim_id'))
    )
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evidence_transformations',
    sa.Column('transformation_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_evidence_id', sa.String(length=64), nullable=False),
    sa.Column('derived_evidence_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.String(length=128), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['derived_evidence_id'], ['evidence_records.evidence_id'], name=op.f('fk_evidence_transformations_derived_evidence_id_evidence_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence_records.evidence_id'], name=op.f('fk_evidence_transformations_source_evidence_id_evidence_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_evidence_transformations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transformation_id', name=op.f('pk_evidence_transformations')),
    sa.UniqueConstraint('source_evidence_id', 'derived_evidence_id', 'operation', name=op.f('uq_evidence_transformations_source_evidence_id'))
    )
    with op.batch_alter_table('evidence_transformations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_transformations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('retests',
    sa.Column('retest_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('procedure_ref', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['remediation_actions.action_id'], name=op.f('fk_retests_action_id_remediation_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], name=op.f('fk_retests_engagement_id_engagements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fk_retests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retest_id', name=op.f('pk_retests'))
    )
    with op.batch_alter_table('retests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retests_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retests_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retests_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_retests_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_retests_action_id'))

    op.drop_table('retests')
    with op.batch_alter_table('evidence_transformations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_transformations_tenant_id'))

    op.drop_table('evidence_transformations')
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_tenant_id'))

    op.drop_table('claim_evidence_links')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_tenant_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_remediation_actions_finding_id'))

    op.drop_table('remediation_actions')
    with op.batch_alter_table('management_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_management_responses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_management_responses_finding_id'))

    op.drop_table('management_responses')
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_traces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_execution_traces_task_id'))
        batch_op.drop_index(batch_op.f('ix_execution_traces_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_execution_traces_agent_release_id'))

    op.drop_table('execution_traces')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_engagement_id'))

    op.drop_table('evidence_records')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_claims_task_id'))
        batch_op.drop_index(batch_op.f('ix_claims_finding_id'))
        batch_op.drop_index(batch_op.f('ix_claims_engagement_id'))

    op.drop_table('claims')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_engagement_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_decisions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_finding_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_engagement_id'))

    op.drop_table('approval_decisions')
    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_schedule_id'))

    op.drop_table('schedule_occurrences')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_findings_engagement_id'))

    op.drop_table('findings')
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_relationships_tenant_id'))

    op.drop_table('entity_relationships')
    with op.batch_alter_table('engagement_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_claimable')
        batch_op.drop_index(batch_op.f('ix_engagement_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engagement_tasks_engagement_id'))

    op.drop_table('engagement_tasks')
    with op.batch_alter_table('risk_control_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_control_links_tenant_id'))

    op.drop_table('risk_control_links')
    with op.batch_alter_table('organization_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_facts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_organization_facts_profile_id'))

    op.drop_table('organization_facts')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engagements_template_id'))

    op.drop_table('engagements')
    with op.batch_alter_table('audit_universe_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_universe_entities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_universe_entities_profile_id'))

    op.drop_table('audit_universe_entities')
    with op.batch_alter_table('audit_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_schedules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_schedules_plan_id'))

    op.drop_table('audit_schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('role_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_assignments_tenant_id'))

    op.drop_table('role_assignments')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_tenant_id'))

    op.drop_table('risks')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_unpublished')
        batch_op.drop_index(batch_op.f('ix_outbox_events_tenant_id'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('organization_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_profiles_tenant_id'))

    op.drop_table('organization_profiles')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_tenant_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('engagement_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_templates_tenant_id'))

    op.drop_table('engagement_templates')
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controls_tenant_id'))

    op.drop_table('controls')
    with op.batch_alter_table('audit_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_plans_tenant_id'))

    op.drop_table('audit_plans')
    op.drop_table('tenants')
    with op.batch_alter_table('agent_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_releases_agent_id'))

    op.drop_table('agent_releases')
    # ### end Alembic commands ###
