"""Finding adjudication, remediation, and independent retest.

The component that turns deterministic control-test results into an audit
conclusion: propose, search for contradictions, gate on a human decision, open a
remediation obligation exactly once, collect closure evidence, and verify it with
an independent retest.
"""

from .definitions import (
    ALLOWED_TRANSITIONS,
    CLOSING_OUTCOMES,
    AdjudicationRequest,
    ClosureSubmission,
    Contradiction,
    ContradictionKind,
    DisputeGround,
    DisputeRequest,
    DisputeResolution,
    DisputeResolutionRequest,
    FindingStatus,
    FindingView,
    HumanDecision,
    MaterialityRequest,
    ProposedFinding,
    QualityReviewRequest,
    RecurrenceMatch,
    RemediationRequest,
    RetestOutcome,
    RetestRequest,
    SeverityOverrideRequest,
    SkepticVerdict,
)
from .exceptions import (
    AdjudicationError,
    ClosureEvidenceError,
    DisputeError,
    FindingNotFoundError,
    HumanGateError,
    IdempotencyConflictError,
    IndependenceError,
    InvalidTransitionError,
    MaterialityError,
    QualityGateError,
    RemediationNotFoundError,
    TicketingError,
)
from .materiality import (
    DEFAULT_FACTOR_WEIGHTS,
    SEVERITY_ORDER,
    FactorAssertion,
    MaterialityInputs,
    MaterialityPolicy,
    MaterialityResult,
    QualitativeFactor,
    assess,
    content_hash,
    severity_rank,
)
from .quality import CheckResult, QualityCheck, QualityReviewOutcome
from .repository import AdjudicationRepository
from .service import AdjudicationService, finding_from_exceptions
from .skeptic import SkepticReviewer
from .ticketing import (
    CORRELATION_PREFIX,
    JiraTicketWriter,
    NullTicketWriter,
    ServiceNowTicketWriter,
    TicketRef,
    TicketRequest,
    TicketWriter,
    correlation_key,
    writer_from_connector,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CLOSING_OUTCOMES",
    "CORRELATION_PREFIX",
    "DEFAULT_FACTOR_WEIGHTS",
    "SEVERITY_ORDER",
    "AdjudicationError",
    "AdjudicationRepository",
    "AdjudicationRequest",
    "AdjudicationService",
    "CheckResult",
    "ClosureEvidenceError",
    "ClosureSubmission",
    "Contradiction",
    "ContradictionKind",
    "DisputeError",
    "DisputeGround",
    "DisputeRequest",
    "DisputeResolution",
    "DisputeResolutionRequest",
    "FactorAssertion",
    "FindingNotFoundError",
    "FindingStatus",
    "FindingView",
    "HumanDecision",
    "HumanGateError",
    "IdempotencyConflictError",
    "IndependenceError",
    "InvalidTransitionError",
    "JiraTicketWriter",
    "MaterialityError",
    "MaterialityInputs",
    "MaterialityPolicy",
    "MaterialityRequest",
    "MaterialityResult",
    "NullTicketWriter",
    "ProposedFinding",
    "QualitativeFactor",
    "QualityCheck",
    "QualityGateError",
    "QualityReviewOutcome",
    "QualityReviewRequest",
    "RecurrenceMatch",
    "RemediationNotFoundError",
    "RemediationRequest",
    "RetestOutcome",
    "RetestRequest",
    "ServiceNowTicketWriter",
    "SeverityOverrideRequest",
    "SkepticReviewer",
    "SkepticVerdict",
    "TicketRef",
    "TicketRequest",
    "TicketWriter",
    "TicketingError",
    "writer_from_connector",
    "assess",
    "content_hash",
    "correlation_key",
    "finding_from_exceptions",
    "severity_rank",
]
